### ISSUE TITLE
Input delay does not respect non character keys

### ISSUE THREAD

**Issue by TimyJ** [TimyJ/GrimDank#4]
The delay is only effective using traditional character and number keys. Key's such as Tab and + do not delay at all.

**Comment by Chris3606** [comment]
First thought is tthis and implementing issue #5 both pertain to fixing some poor assumptions of the current input handling code about one key being pressed, and in this case whether modifier keys are actually included in the list of keys being iterated through by InputStack.  I'll see what can be done as soon as I can get a devvable computer.

**Comment by Chris3606** [comment]
Haven't been able to replicate this using tab or + on the master branch code.  Perhaps something has changed in input code since master?

Otherwise, this could be caused by returning false from an input handling function even if a key is handled.  The input delay sets itself based on the return value of input handlers (whether or not a key was actually handled).

If that's the case, this may be a side effect of bad practice in the InputStack code -- key input delay is reset to "unpressed" state if any key was released, but is set to pressed iff an input handler function returns true (eg, a key was actually handled).  This was quick for me to write at the time, however could probably be written to be more consistent -- regardless of the cause of this particular issue, if this is something we want to pursue, we can definately create another issue for it -- especially because it pushes toward potentially rewriting large portions of the delay code to be more consistent with MonoGame input handling options.

**Comment by Chris3606** [comment]
Most recent commit to master should fix up targeting issues.  Will leave open for final determination, on whether or not it warrants changing how input handling works?

Thinking it might (big might???) be cleaner to pass a key that was pressed, and an enum on special character state as in the cross-referenced issue, instead of a full keyboard state.  Would at least allow for cleaner use of the switch statement.

Otherwise, would be worth not passing the keyboard state if nothing is pressed anyway.
